<Cookie>:
    BoxLayout:
        orientation: 'horizontal'    # Ustawienie orientacji: 'horizontal' to od lewej do prawej
        size_hint: (1, None)         # Szerokość: 1 (100% okna), Wysokość: None (wyłączamy automat)
        height: '50dp'               # Ustalamy sztywną wysokość na 50 jednostek dp (idealne pod palec)
        pos_hint: {'top': 1}         # Przyklejamy ten pasek do samej góry ekranu (top = 1.0)

        spacing: '10dp'               # Odstęp (pusta przestrzeń) pomiędzy przyciskami
        padding: '10dp'               # Margines wewnętrzny (odstęp przycisków od krawędzi paska)

        Button:
            text: "Start"
            canvas.after:
                Color:
                    rgba: 1, 1, 1, 1
                Line:
                    width: 2
                    rectangle: (self.x, self.y, self.width, self.height)
        Button:
            text: "Galeria"



        Button:
            text: "Opcje"


        Button:
            text: "Wyjdź"
            on_release: app.stop()